services:
  # Flask application
  web:
    build: .
    container_name: fansboda-web
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
    volumes:
      - ./static:/app/static:ro # Mount static files for nginx
    networks:
      - fansboda-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: fansboda-nginx
    restart: unless-stopped
    ports:
      - "80:80" # HTTP - redirects to HTTPS
      - "443:443" # HTTPS - main application
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/var/www/static:ro
      - ./certificates:/etc/nginx/ssl:ro # Mount SSL certificates
    depends_on:
      web:
        condition: service_healthy
    networks:
      - fansboda-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  fansboda-network:
    driver: bridge

