name: Deploy to Cloud Run
run-name: ${{ github.actor }} is deploying to Cloud Run  🚀
on: 
  workflow_run:
      workflows: ["Build and Test"] # Run the deploy after successful Build and Test
      types:
        - completed     

jobs:
  deploy_to_cloud_run:
    runs-on: ubuntu-latest

    # env:
    #   PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    #   SVC_ACCOUNT: ${{ secrets.GCP_SVC_ACCOUNT }}
    #   GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/${{ secrets.GCP_SVC_ACCOUNT }}.json
    #   SVC_ACCOUNT_EMAIL: ${{ secrets.GCP_SVC_ACCOUNT }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
    #   REGION: ${{ vars.GCP_REGION }} 

 
    steps:
    - uses: actions/checkout@v4

    # - name: Check env vars
    #   run: |
    #     echo "Environment variables configured:"
    #     echo PROJECT_ID="$PROJECT_ID"
    #     echo REGION="$REGION"
    #     echo SVC_ACCOUNT="$SVC_ACCOUNT"
    #     echo SVC_ACCOUNT_EMAIL="$SVC_ACCOUNT_EMAIL"
    #     echo GOOGLE_APPLICATION_CREDENTIALS="$GOOGLE_APPLICATION_CREDENTIALS"

      
    
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SVC_ACCOUNT_CREDS }}
      
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev

    - name: Build and Push Docker image
      run: |
        IMAGE_URI="${{ vars.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gh-fansboda-repo/fansboda:latest"
        docker build -t "$IMAGE_URI" .
        docker push "$IMAGE_URI"
      

   
     
