name: Deploy to Cloud Run
run-name: ${{ github.actor }} is deploying to Cloud Run  🚀
on: 
  workflow_run:
      workflows: ["Build and Test"] # Run the deploy after successful Build and Test
      types:
        - completed     

jobs:
  deploy_to_cloud_run:
    runs-on: ubuntu-latest


    
    steps:
    - uses: actions/checkout@v4


      

   
     
