name: Deploy to Cloud Run
run-name: ${{ github.actor }} is deploying to Cloud Run  🚀
on: 
  workflow_run:
      workflows: ["Build and Test"] # Run the deploy after successful Build and Test
      types:
        - completed     

jobs:
  deploy_to_cloud_run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Creates a credentials file that will be used for ADC later
    - name: Create credentials file
      run: |
        echo "${{ secrets.GCP_SVC_ACCOUNT_CREDS }}" | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS

      

   
        credentials_json: $GOOGLE_APPLICATION_CREDENTIALS
