name: 3. Deploy to Cloud Run
run-name: ${{ github.actor }} is deploying to Cloud Run  🚀
on: 
  workflow_run:
      workflows: ["2. Build and Test"] # Run the deploy after successful Build and Test
      types:
        - completed     

jobs:
  deploy_to_cloud_run:
    runs-on: ubuntu-latest

    # env:
    #   PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    #   SVC_ACCOUNT: ${{ secrets.GCP_SVC_ACCOUNT }}
    #   GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/${{ secrets.GCP_SVC_ACCOUNT }}.json
    #   SVC_ACCOUNT_EMAIL: ${{ secrets.GCP_SVC_ACCOUNT }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
    #   REGION: ${{ vars.GCP_REGION }} 

 
    steps:
    - uses: actions/checkout@v4

    # - name: Check env vars
    #   run: |
    #     echo "Environment variables configured:"
    #     echo PROJECT_ID="$PROJECT_ID"
    #     echo REGION="$REGION"
    #     echo SVC_ACCOUNT="$SVC_ACCOUNT"
    #     echo SVC_ACCOUNT_EMAIL="$SVC_ACCOUNT_EMAIL"
    #     echo GOOGLE_APPLICATION_CREDENTIALS="$GOOGLE_APPLICATION_CREDENTIALS"

    # - name: Decode Google Cloud Service Account Credentials
    #   run: |
    #     echo "${{ secrets.GCP_SVC_ACCOUNT_CREDS }}" | base64 --decode | jq > gcp-credentials.json
    #     export "GOOGLE_APPLICATION_CREDENTIALS=gcp-credentials.json"
    
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: "${{ secrets.GCP_SVC_ACCOUNT_CREDS }}"
      
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
      
    - name: Set up gcloud beta
      run: gcloud components install beta

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev

    - name: Build and Push Docker image
      run: |
        IMAGE_URI="${{ vars.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ vars.GCP_REPO }}/${{ vars.GCP_IMAGE_NAME }}:${{ github.run_number }}"
        docker build -t "$IMAGE_URI" .
        docker push "$IMAGE_URI"
    
    - name: Deploy to Cloud Run
      run: |
        gcloud beta run deploy ${{ vars.GCP_IMAGE_NAME }}  \
          --image "${{ vars.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ vars.GCP_REPO }}/${{ vars.GCP_IMAGE_NAME }}:${{ github.run_number }}" \
          --platform managed \
          --region ${{ vars.GCP_REGION }} \
          --port 8080 \
          --memory 512Mi \
          --cpu 1 \
          --max-instances 1 \
          --project ${{ secrets.GCP_PROJECT_ID  }} \
          --service-account ${{ secrets.GCP_SVC_ACCOUNT }} \
          --allow-unauthenticated
 
    - name: Assign custom service account to Cloud Run service
      run: |
        gcloud run services update ${{ vars.GCP_SERVICE_NAME }} \
        --region ${{ vars.GCP_REGION }} \
        --service-account ${{ secrets.GCP_SVC_ACCOUNT }}      

   
     
